#!/bin/bash
set -euo pipefail

BASE="/share/lab_crd/lab_crd/HighPloidy_CostBenefits/data/BreastCancerCellLines/SUM-159/N01_Incucyte_SUM159_Doxorubicin_Test1"
PROJECT_DIR="$BASE/cellpose-cpsam-pipeline_v2"
INPUT_ROOT="$BASE/20260619_SUM159_Doxorubicin_Cyclophosphamide/20260626_SUM159_AC_Exp1_SeparateImages"
RESULTS_ROOT="$BASE/20260619_SUM159_Doxorubicin_Cyclophosphamide/results"

STAMP="$(date +%Y%m%d_%H%M%S)"
OUT_ROOT="$RESULTS_ROOT/full_fusion_shape_strict_${STAMP}"

export PROJECT_DIR
export INPUT_ROOT
export OUT_ROOT
export RUN_NAME="."

export EXPECTED_SUBDIRS=4
export EXPECTED_IMAGES=108800
export SKIP_SUBDIRS="Dead_Uncalibrated"

export ENABLE_HIGH_DENSITY_PROFILES=1
export AUTO_GENERATE_DENSITY_CALLS=1
export DENSITY_CALLS_NAME="density_calls.csv"

# Final classification is generated by 29_fuse_multichannel_classification.py.
export SEGMENTATION_ONLY=1
export FORCE_CLASSIFICATION=0

export SBATCH_JOB_NAME="cpsam_full_fusion"
export SBATCH_TIME="12:00:00"
export SBATCH_CPUS=2
export SBATCH_MEM="8G"
export SBATCH_QOS="xxlarge"
export SBATCH_GRES="gpu:a30:1"

export NUCLEI_SBATCH_TIME="$SBATCH_TIME"
export NUCLEI_SBATCH_CPUS="$SBATCH_CPUS"
export NUCLEI_SBATCH_MEM="$SBATCH_MEM"

export DENSITY_TABLE_SBATCH_TIME="12:00:00"
export DENSITY_TABLE_SBATCH_CPUS=1
export DENSITY_TABLE_SBATCH_MEM="8G"
export DENSITY_TABLE_SBATCH_QOS="xxlarge"

export ENABLE_FUSION_CLASSIFICATION=1
export FUSION_OUT_DIR="$OUT_ROOT/classification_fusion"
export FUSION_SBATCH_TIME="12:00:00"
export FUSION_SBATCH_CPUS=1
export FUSION_SBATCH_MEM="4G"
export FUSION_SBATCH_QOS="xxlarge"
export FUSION_MERGE_SBATCH_TIME="12:00:00"
export FUSION_MERGE_SBATCH_CPUS=1
export FUSION_MERGE_SBATCH_MEM="8G"
export FUSION_MERGE_SBATCH_QOS="xxlarge"

export ENABLE_SHAPE_STRICT=1
export SHAPE_ROOT="$OUT_ROOT/shape_strict"
export SHAPE_SBATCH_TIME="12:00:00"
export SHAPE_SBATCH_CPUS=1
export SHAPE_SBATCH_MEM="8G"
export SHAPE_SBATCH_QOS="xxlarge"
export SHAPE_FINALIZE_SBATCH_TIME="12:00:00"
export SHAPE_FINALIZE_SBATCH_CPUS=1
export SHAPE_FINALIZE_SBATCH_MEM="16G"
export SHAPE_FINALIZE_SBATCH_QOS="xxlarge"
export SHAPE_MAX_QC_FIELDS=24
export SHAPE_MAX_CROPS_PER_FIELD=8
export SHAPE_QC_CROP_SIZE=224

mkdir -p "$OUT_ROOT"

echo "project_dir=$PROJECT_DIR"
echo "input_root=$INPUT_ROOT"
echo "out_root=$OUT_ROOT"
echo "fusion_out_dir=$FUSION_OUT_DIR"
echo "segmentation_qos=$SBATCH_QOS"
echo "fusion_qos=$FUSION_SBATCH_QOS"
echo "fusion_merge_qos=$FUSION_MERGE_SBATCH_QOS"
echo "density_qos=$DENSITY_TABLE_SBATCH_QOS"
echo "shape_root=$SHAPE_ROOT"
echo "shape_qos=$SHAPE_SBATCH_QOS"
echo "shape_finalize_qos=$SHAPE_FINALIZE_SBATCH_QOS"

bash "$PROJECT_DIR/cellpose_pipeline/hpc/submit_cellpose_cpsam_full_array.sh"
